#datas
email =testlogin@gmail.com
Email=testlogin1@gmail.com
message=An email with a confirmation link has been sent your email address.
error_message=Warning: The E-Mail Address was not found in our records, please try again!